# Generated by Django 3.2.25 on 2025-05-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='Apellido',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='Ciudad',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='Codigo_postal',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='Dirrecion',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='first_name',
            new_name='Nombre',
        ),
    ]
