# Generated by Django 5.2.1 on 2025-05-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
