# Generated by Django 5.2.1 on 2025-05-21 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
        ('shop', '0005_alter_customerinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleordencompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
