# Generated by Django 3.2.25 on 2025-05-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
