# Generated by Django 5.2.1 on 2025-05-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_customerinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerinfo',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Customer Info', 'verbose_name_plural': 'Customer Infos'},
        ),
        migrations.AddIndex(
            model_name='customerinfo',
            index=models.Index(fields=['apellido', 'nombre'], name='shop_custom_apellid_87d8bd_idx'),
        ),
    ]
